/**
 * IA Loop — real git operations.
 *
 * All git access goes through here so the orchestrator collects the repository
 * state itself instead of trusting what a model claims it changed.
 *
 * Read helpers are safe by construction. The only mutating operation is
 * `createWorktree`, which refuses to force, reset or delete anything.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { access } from 'node:fs/promises';
import { join } from 'node:path';

import { SpikeError } from './claude-process.mjs';

const execFileAsync = promisify(execFile);

/**
 * Paths regenerated by tooling. Their dirtiness is expected and does not block;
 * anything else dirty does.
 */
export const REGENERATED_PATHS = Object.freeze(['graphify-out']);

/** Runs git, returning trimmed stdout. Throws SpikeError on failure. */
export async function git(args, { cwd, timeoutMs = 120_000, maxBuffer = 64 * 1024 * 1024 } = {}) {
  try {
    const { stdout } = await execFileAsync('git', args, { cwd, timeout: timeoutMs, maxBuffer });
    return stdout.trim();
  } catch (error) {
    throw new SpikeError('GIT_FAILED', `git ${args.slice(0, 3).join(' ')} failed: ${error.message}`, {
      args,
      cwd,
    });
  }
}

/** Same, but returns null instead of throwing — for existence probes. */
async function gitOrNull(args, options) {
  try {
    return await git(args, options);
  } catch {
    return null;
  }
}

export function createGitProbe(repoRoot) {
  return {
    repoRoot,

    currentBranch() {
      return git(['rev-parse', '--abbrev-ref', 'HEAD'], { cwd: repoRoot });
    },

    head() {
      return git(['rev-parse', 'HEAD'], { cwd: repoRoot });
    },

    /**
     * Dirtiness excluding regenerated paths.
     *
     * The exclusion is delegated to git rather than parsed by column offset:
     * trimming git's output eats the leading status space of the first line.
     */
    async isDirty() {
      const status = await git(
        ['status', '--porcelain', '--', '.', ...REGENERATED_PATHS.map((p) => `:(exclude)${p}`)],
        { cwd: repoRoot },
      );
      return status !== '';
    },

    async relevantDirtyFiles() {
      const status = await git(
        ['status', '--porcelain', '--', '.', ...REGENERATED_PATHS.map((p) => `:(exclude)${p}`)],
        { cwd: repoRoot },
      );
      return status === '' ? [] : status.split('\n').map((l) => l.slice(3)).filter(Boolean);
    },

    async branchExists(name) {
      return (await gitOrNull(['rev-parse', '--verify', `refs/heads/${name}`], { cwd: repoRoot })) !== null;
    },

    async commitExists(sha) {
      return (await gitOrNull(['rev-parse', '--verify', `${sha}^{commit}`], { cwd: repoRoot })) !== null;
    },

    /**
     * Is this commit in the history HEAD is standing on?
     *
     * Deliberately stronger than `commitExists`: a commit can sit in the object
     * database after a reset, an abandoned branch or a fetch without being part
     * of what the repository currently says happened. Anything that reads a
     * recorded sha as proof that work LANDED needs reachability, not existence.
     */
    async isAncestorOfHead(sha) {
      if (typeof sha !== 'string' || sha.trim() === '') return false;
      return (await gitOrNull(['merge-base', '--is-ancestor', sha, 'HEAD'], { cwd: repoRoot })) !== null;
    },

    async worktrees() {
      const out = await git(['worktree', 'list', '--porcelain'], { cwd: repoRoot });
      const entries = [];
      let current = null;
      for (const line of out.split('\n')) {
        if (line.startsWith('worktree ')) {
          if (current) entries.push(current);
          current = { path: line.slice('worktree '.length), branch: null };
        } else if (line.startsWith('branch ') && current) {
          current.branch = line.slice('branch '.length);
        }
      }
      if (current) entries.push(current);
      return entries;
    },

    async pathExists(relPath) {
      try {
        await access(join(repoRoot, relPath));
        return true;
      } catch {
        return false;
      }
    },
  };
}

/**
 * Collects the REAL change surface of a worktree against a base commit.
 *
 * Deliberately not taken from the model's own report: the repository is the
 * authority on what changed.
 */
export async function collectWorktreeChanges(worktreePath, baseSha, { maxDiffBytes = 4 * 1024 * 1024 } = {}) {
  const opts = { cwd: worktreePath };

  const head = await git(['rev-parse', 'HEAD'], opts);
  const branch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], opts);
  const status = await git(['status', '--porcelain'], opts);

  // Commits the base does not have. Must stay empty: the Developer may not commit.
  const commitsRaw = await git(['log', '--oneline', `${baseSha}..HEAD`], opts);
  const commits = commitsRaw === '' ? [] : commitsRaw.split('\n');

  // Tracked changes against the base, plus untracked files, which a diff misses.
  const trackedRaw = await git(['diff', '--name-only', baseSha, '--'], opts);
  const tracked = trackedRaw === '' ? [] : trackedRaw.split('\n').filter(Boolean);

  const untrackedRaw = await git(['ls-files', '--others', '--exclude-standard'], opts);
  const untracked = untrackedRaw === '' ? [] : untrackedRaw.split('\n').filter(Boolean);

  const changedFiles = [...new Set([...tracked, ...untracked])].sort();
  const diffStat = await git(['diff', '--stat', baseSha, '--'], opts);

  let diff = await git(['diff', baseSha, '--'], opts, { maxBuffer: maxDiffBytes });
  let diffTruncated = false;
  if (diff.length > maxDiffBytes) {
    diff = diff.slice(0, maxDiffBytes);
    diffTruncated = true;
  }

  return {
    base: baseSha,
    head,
    branch,
    changedFiles,
    untracked,
    commits,
    diffStat,
    diff,
    diffTruncated,
    statusPorcelain: status,
    clean: status === '' && changedFiles.length === 0,
  };
}

/**
 * A cheap fingerprint of the worktree's content, used to prove the reviewer did
 * not modify anything.
 */
export async function worktreeFingerprint(worktreePath) {
  const opts = { cwd: worktreePath };
  const head = await git(['rev-parse', 'HEAD'], opts);
  const status = await git(['status', '--porcelain'], opts);
  // Hashes staged+unstaged content of tracked files.
  const treeHash = await git(['stash', 'create'], opts).catch(() => '');
  return { head, status, treeHash };
}

/**
 * Creates the worktree for real.
 *
 * Only ever runs `git worktree add -b <branch> <path> <base>`. No force, no
 * reset, no delete, no checkout of the main working copy.
 */
export async function createWorktree({ repoRoot, path, branch, base }) {
  if (!repoRoot || !path || !branch || !base) {
    throw new SpikeError('INVALID_ARGS', 'repoRoot, path, branch and base are required');
  }

  const output = await git(['worktree', 'add', '-b', branch, path, base], {
    cwd: repoRoot,
    timeoutMs: 300_000,
  });

  const created = join(repoRoot, path);
  const head = await git(['rev-parse', 'HEAD'], { cwd: created });
  const createdBranch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], { cwd: created });

  if (head !== base) {
    throw new SpikeError(
      'WORKTREE_HEAD_MISMATCH',
      `Worktree HEAD ${head} does not match the requested base ${base}`,
    );
  }
  if (createdBranch !== branch) {
    throw new SpikeError(
      'WORKTREE_BRANCH_MISMATCH',
      `Worktree is on branch ${createdBranch}, expected ${branch}`,
    );
  }

  return { path: created, branch: createdBranch, head, output };
}

/**
 * Stages selected paths and creates a commit inside a worktree.
 *
 * The staging is explicit: `git add .` is never used, so tooling, regenerated
 * artefacts and unrelated changes cannot ride along.
 */
export async function stageAndCommit({ cwd, paths, message, excludePaths = [] }) {
  if (!cwd || !message) throw new SpikeError('INVALID_ARGS', 'cwd and message are required');
  if (!Array.isArray(paths) || paths.length === 0) {
    throw new SpikeError('INVALID_ARGS', 'at least one path must be staged');
  }

  // Chunked: a Goal can touch dozens of files and argv has a limit.
  const CHUNK = 40;
  for (let i = 0; i < paths.length; i += CHUNK) {
    await git(['add', '--', ...paths.slice(i, i + CHUNK)], { cwd });
  }

  for (const excluded of excludePaths) {
    await git(['reset', '-q', 'HEAD', '--', excluded], { cwd }).catch(() => {});
  }

  const staged = await git(['diff', '--cached', '--name-only'], { cwd });
  if (staged === '') {
    throw new SpikeError('NOTHING_TO_COMMIT', 'No staged changes; refusing to create an empty commit');
  }

  await git(['commit', '-m', message], { cwd, timeoutMs: 300_000 });
  const sha = await git(['rev-parse', 'HEAD'], { cwd });

  return { sha, stagedFiles: staged.split('\n').filter(Boolean) };
}

/** True when a cherry-pick is half-finished and must be resolved first. */
export async function cherryPickInProgress(repoRoot) {
  const dir = await git(['rev-parse', '--git-dir'], { cwd: repoRoot });
  const path = join(repoRoot, dir, 'CHERRY_PICK_HEAD');
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Applies an accepted commit onto the main checkout.
 *
 * A conflict is aborted, never resolved automatically: the orchestrator has no
 * authority to decide how two changes should be merged.
 */
export async function cherryPick({ repoRoot, sha }) {
  if (await cherryPickInProgress(repoRoot)) {
    throw new SpikeError('CHERRY_PICK_IN_PROGRESS', 'A cherry-pick is already in progress; resolve it first');
  }

  const before = await git(['rev-parse', 'HEAD'], { cwd: repoRoot });
  try {
    await git(['cherry-pick', '-x', sha], { cwd: repoRoot, timeoutMs: 300_000 });
  } catch (error) {
    await git(['cherry-pick', '--abort'], { cwd: repoRoot }).catch(() => {});
    throw new SpikeError(
      'CHERRY_PICK_CONFLICT',
      `Cherry-pick of ${sha} did not apply cleanly and was aborted. A human must integrate it.`,
      { sha, before },
    );
  }

  const after = await git(['rev-parse', 'HEAD'], { cwd: repoRoot });
  if (after === before) {
    throw new SpikeError('CHERRY_PICK_NOOP', `Cherry-pick of ${sha} produced no commit`);
  }
  return { before, after };
}

/** Whether a commit is already reachable from HEAD (by content or by note). */
export async function isAlreadyIntegrated({ repoRoot, sha }) {
  // `-x` records the source sha in the message, so a repeated closure is
  // detectable even though the cherry-pick created a different commit id.
  const log = await git(['log', '--grep', `cherry picked from commit ${sha}`, '--format=%H', '-n', '1'], { cwd: repoRoot })
    .catch(() => '');
  return log !== '';
}
